### ISSUE TITLE
对于iOS客户端是否需要考虑字节序的问题？

### ISSUE THREAD

**Issue by chipengliu** [TheBloodElf/IMSocketClient#5]
iOS系统目前采用的是小端序。如果在进行socket网络传输之类的工作时，是否得考虑先把字节序进行转换，然后再传输？

**Comment by TheBloodElf** [comment]
https://blog.csdn.net/ce123_zhouwei/article/details/6971544
https://blog.csdn.net/lincyang/article/details/17266027
一般是不需要处理的，手机处理器是ARM，一般是小端序

**Comment by TheBloodElf** [comment]
一般是不需要处理的，手机处理器是ARM，一般是小端序。

**Comment by chipengliu** [comment]
![image](https://user-images.githubusercontent.com/16236724/39659322-69e8eaa8-5058-11e8-9955-79802aaf3db1.png)
http://beginman.cn/unp/2015/10/15/unp-socket/
手机都是小端，但是服务器或者pc除了MacOS大多数都是大端，我个人觉得有必要处理的
